---
# yamllint configuration

extends: default
ignore-from-file: [.gitignore, .yamlignore]

rules:
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
  empty-lines:
    max: 3
    max-start: 1
    max-end: 1
  indentation:
    spaces: 2
    indent-sequences: true
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  new-line-at-end-of-file: enable
