---
- name: Configure Windows Server 2025 hosts
  hosts: all

  vars:
    ansible_shell_type: powershell

  tasks:
    - name: Make sure Windows Features (that I need) are installed
      ansible.windows.win_feature:
        name:
          - Windows-Defender
          - PowerShell
          - WoW64-Support
          - NET-Framework-Core # .NET 3.5

    # Note:
    #  - OpenSSH comes with OS by default, after Windows Server 2025
    - name: Make sure Windows Optional Features (that I need) are installed
      ansible.builtin.win_optional_feature:
        name:
          - Microsoft-RemoteDesktopConnection
        state: present

    # - name: Make sure Windows Optional Features (that I don't need) are not installed
    #   ansible.builtin.win_optional_feature:
    #     name:
    #       - AzureArcSetup
    #     state: absent

    # TODO: Configure incoming firewall rule
    # - name: Make sure incoming firewall rules are correctly configured


    - name: Make sure default shell of OpenSSH is powershell
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\OpenSSH'
        name: DefaultShell
        type: string
        data: 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe'
        state: present

    - name: Make sure OpenSSH sshd is configured to automatically start on boot
      ansible.windows.win_service:
        name: sshd
        start_mode: auto
        state: started

    - name: Registry - Prevent Network Access to OneDrive before the user activity
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\OneDrive'
        name: PreventNetworkTrafficPreUserSignIn
        data: 1
        type: dword
        state: present

    # - name: Registry
    #   ansible.windows.win_regedit:
    #     path: 'HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\SQM'
    #     name: MicrosoftEdgeDataOptIn
    #     data: 0
    #     type: dword
    #     state: present

    - name: Debloat Microsoft Edge
      block:
        - name: a
          ansible.windows.win_regedit:
            path: 'HKLM:\SOFTWARE\Policies\Microsoft\Edge'
            name: "{{ item }}"
            data: 0
            type: dword
            state: present
          loop:
            - HubsSidebarEnabled
            - ReadAloudEnabled
            - DiagnosticData
            - EdgeCollectionsEnabled
            - PersonalizationReportingEnabled
            - ShowMicrosoftRewards
            - EdgeWalletCheckoutEnabled
            - EdgeWalletEtreeEnabled
            - SpellcheckEnabled
            - AddressBarWorkSearchResultsEnabled
            - AddressBarTrendingSuggestEnabled
            - StartupBoostEnabled
            - AutoplayAllowed
            - QRCodeGeneratorEnabled
            - TranslateEnabled
            - CopilotPageContext
            - CopilotPageContextEnabled
            - DesktopSharingHubEnabled
            - AIGenThemesEnabled
            - ShowAcrobatSubscriptionButton
            - ShowRecommendationsEnabled

        # - name: Include common playbook
        #   ansible.builtin.import_playbook: configure_windows_common.yml

    # - name: Update group policy
    #   ansible.windows.win_shell: |
    #     gpupdate.exe /Target:Computer /Force
    #     gpupdate.exe /Target:User /Force
    #   args:
    #     no_profile: true

    # - name: Reboot
    #   when: not ansible_check_mode
    #   ansible.windows.win_reboot:
