---
- name: Configure RHEL(-like) systems
  hosts: all
  become: true

  vars:
    ansible_facts_modules:
      - setup
      - ansible.posix.rhel_facts

  pre_tasks:
    - name: Assert that ansible_os_family is equal to 'RedHat'
      ansible.builtin.assert:
        that: ansible_os_family == 'RedHat'
        success_msg: 'ansible_os_family is "RedHat"'
        fail_msg: 'ansible_os_family is not "RedHat"'
      tags:
        - always

  tasks:
    - name: Configure NetworkManager to use glibc resolver
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version|int >= 8
      community.general.ini_file:
        path: /etc/NetworkManager/conf.d/99_reishoku.conf
        section: main
        option: dns
        value: none

    - name: Ensure packages are installed
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name:
          - bash
          - bsdtar
          - cmake
          - curl
          - git
          - git-core-doc
          - glibc
          - go-toolset
          - kernel
          - kernel-devel
          - kernel-devel-matched
          - kernel-doc
          - kernel-modules
          - kernel-tools
          - openssh
          - openssh-clients
          - openssh-server
          - python3
          - rust-toolset
          - sshpass
          - tar
          - tuned
          - xz
          - xz-libs
          - xz-lzma-compat
        state: installed
        install_weak_deps: false
