---
- name: Configure RHEL(-like) systems
  hosts: all
  become: true

  tasks:
    - name: Configure NetworkManager to use glibc resolver
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version|int >= 8
      community.general.ini_file:
        path: /etc/NetworkManager/conf.d/99_reishoku.conf
        section: main
        option: dns
        value: none

    - name: Ensure packages are installed
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name:
          - bsdtar
          - cmake
          - curl
          - git
          - git-core-doc
          - glibc
          - go-toolset
          - kernel
          - kernel-devel
          - kernel-devel-matched
          - kernel-doc
          - kernel-modules
          - kernel-tools
          - openssh
          - openssh-clients
          - openssh-server
          - python3
          - rust-toolset
          - sshpass
          - tar
          - tuned
          - xz
          - xz-libs
          - xz-lzma-compat
        state: installed
