---
- name: Common configuration between client Windows and Windows Server
  hosts: all

  vars:
    ansible_shell_type: powershell

  tasks:
    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Disallow cloud integration
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Dsh', name: 'AllowNewsAndInterests', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'AllowCloudSearch', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'ConnectedSearchUseWeb', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableWindowsConsumerFeatures', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent', name: 'DisableTailoredExperiencesWithDiagnosticData', data: '1', type: 'dword', state: 'present' }

    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Disable AI related features
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot', name: 'TurnOffWindowsCopilot', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'AllowRecallEnablement', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'DisableAIDataAnalysis', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'DisableClickToDo', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsNotepad', name: 'DisableAIFeatures', data: '1', type: 'dword', state: 'present' }

    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Configure Look and Feel
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', name: 'ShowTaskViewButton', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarAl', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarSi', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarDa', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'Start_Layout', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'Start_IrisRecommendations', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'LaunchTo', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarSd', name: 'SystemSettings_DesktopTaskbar_Sd', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarSn', name: 'SystemSettings_DesktopTaskbar_Sn', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search', name: 'SearchboxTaskbarMode', data: '0', type: 'dword', state: 'present' }

    - name: Disable some typing features
      ansible.windows.win_regedit:
        path:  'HKLM:\SOFTWARE\Microsoft\input\Settings'
        name:  "{{ item }}"
        data:  0
        type:  dword
        state: present
      loop:
        - EnableAutoShiftEngage
        - EnableDoubleTapSpace
        - EnableAutocorrection
        - IsVoiceTypingKeyEnabled

    - name: Uncategorized, but needed
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Microsoft\OneDrive', name: 'PreventNetworkTrafficPreUserSignin', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI', name: 'EnumerateAdministrators', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection', name: 'MicrosoftEdgeDataOptIn', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection', name: 'DoNotShowFeedbackNotifications', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection', name: 'AllowTelemetry', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoInternetOpenWith', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoPublishingWizard', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoOnlinePrintsWizard', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\PenWorkspace', name: 'PenWorkspaceButtonDesiredVisibility', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications', name: 'NoCloudApplicationNotification', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\System\CurrentControlSet\Services\wlidsvc', name: 'Start', data: '4', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator', name: 'NoActiveProbe', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Maps', name: 'AllowUntriggeredNetworkTrafficOnSettingsPage', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive', name: 'DisableFileSyncNGSC', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feed', name: 'EnableFeeds', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\TCPIP\v6Transition', name: 'Teledo_State', data: 'Disabled', type: 'string', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization', name: 'DODownloadMode', data: '99', type: 'dword', state: 'present' }

    - name: Systems with Windows 10/11, Windows Server 2025 - Ensure winget is installed
      ansible.windows.win_get_url:
        url: https://github.com/microsoft/winget-cli/releases/download/v1.11.430/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
        dest: '%TEMP%\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.v1.11.430.msixbundle'
      register: winget_installer

    - name: Ensure winget is installed
      ansible.windows.win_package:
        path: "{{ winget_installer.dest }}"
        state: present

    - name: Accept source agreements on winget
      ansible.windows.win_powershell:
        script: |
           winget list --accept-source-agreements -s winget | Out-Null
      changed_when: false
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Systems with Windows 10/11, Windows Server 2025 - Ensure PowerShell 7 is installed
      ansible.windows.win_get_url:
        url: https://github.com/PowerShell/PowerShell/releases/download/v7.5.2/PowerShell-7.5.2.msixbundle
        dest: '%TEMP%\PowerShell-7.5.2.msixbundle'
      register: pwsh_installer

    - name: Ensure PowerShell 7 is installed
      ansible.windows.win_package:
        path: "{{ pwsh_installer.dest }}"
        state: present
