---
- name: Common configuration between client Windows and Windows Server
  hosts: all

  vars:
    ansible_shell_type: powershell

  tasks:
    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Disallow cloud integration
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Dsh', name: 'AllowNewsAndInterests', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'AllowCloudSearch', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search', name: 'ConnectedSearchUseWeb', data: '0', type: 'dword', state: 'present' }

    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Disable AI related features
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot', name: 'TurnOffWindowsCopilot', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'AllowRecallEnablement', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'DisableAIDataAnalysis', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', name: 'DisableClickToDo', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsNotepad', name: 'DisableAIFeatures', data: '1', type: 'dword', state: 'present' }

    - name: Systems with Windows 11 / Windows Server 2025 (or higher) - Configure Look and Feel
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarAl', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarSi', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'TaskbarDa', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'Start_Layout', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'Start_IrisRecommendations', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarSd', name: 'SystemSettings_DesktopTaskbar_Sd', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarSn', name: 'SystemSettings_DesktopTaskbar_Sn', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\ShowTaskViewButton', name: 'SystemSettings_DesktopTaskbar_TaskView', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search', name: 'SearchboxTaskbarMode', data: '0', type: 'dword', state: 'present' }

    - name: Disable some typing features
      ansible.windows.win_regedit:
        path:  'HKLM:\SOFTWARE\Microsoft\input\Settings'
        name:  "{{ item }}"
        data:  0
        type:  dword
        state: present
      loop:
        - EnableAutoShiftEngage
        - EnableDoubleTapSpace
        - EnableAutocorrection
        - IsVoiceTypingKeyEnabled

    - name: Uncategorized, but needed
      ansible.windows.win_regedit:
        path:  "{{ item.path  }}"
        name:  "{{ item.name  }}"
        data:  "{{ item.data  }}"
        type:  "{{ item.type  }}"
        state: "{{ item.state }}"
      loop:
        - { path: 'HKLM:\SOFTWARE\Microsoft\OneDrive', name: 'PreventNetworkTrafficPreUserSignin', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI', name: 'EnumerateAdministrators', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection', name: 'MicrosoftEdgeDataOptIn', data: '0', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoInternetOpenWith', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoPublishingWizard', data: '1', type: 'dword', state: 'present' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'NoOnlinePrintsWizard', data: '1', type: 'dword', state: 'present' }

